version: '2'
services:
#  nginx:
#    image: nginx:latest
#    ports:
#        - "8080:80"
#        - "443:443"
#    links:
#        - php
#    volumes:
#        - ./:/var/www/mongo-client
#        - ./docker-files/nginx/mongo-client.conf:/etc/nginx/conf.d/mongo-client.conf
#        - ./docker-files/error.log:/var/log/nginx/mongo-client-error.log
#    restart: always
  mongo:
    image: mongo:latest
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - ./docker-files/mongo:/data/db
  php:
    image: serkin/php7-fpm-mongodb
    volumes:
      - ./:/var/www/mongo-client
    links:
      - mongo
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.0.104 remote_enable=1"
